### PR TITLE
fix user access token deletion (fix #186)

### LINKED ISSUE #186: Error: username differs from your username, deletion aborted
hub-tool token rm $UUID

WARNING: This action is irreversible.
By confirming, you will permanently delete the access token.
Deleting a token will invalidate your credentials on all Docker clients currently authenticated with this token.

Please type your username "" to confirm deletion: developer
Error: "developer" differs from your username, deletion aborted

username is correct any idea ??

### PR DESCRIPTION
**Pull request by converge**
**- What I did**

As reported on #186, user token deletion is failing to delete user access tokens. The issue is caused by the missing username at the `hubClient.AuthConfig.Username` struct field, the confirmation step looks for the username to confirm, but the username information is empty/not set.

**- How I did it**

At initialization, the `auth, err := store.GetAuth()` is called, I got it in advance, and provided the authorization data to the struct.

**- How to verify it**

1. create a new user token via `hub-tool token create`
2. delete the user token via `hub-tool token rm uuid-token`
3. the confirmation step will now show the username, and the username can be confirmed.

**- Description for the changelog**

Fix user token deletion by adding missing authorization data to the hubClient.

**- A picture of a cute animal (not mandatory)**

### CODE REVIEW

File: internal/commands/token/rm.go [hunk 1]
```diff
@@ -67,11 +67,12 @@ func runRemove(streams command.Streams, hubClient *hub.Client, opts removeOption
 	}
 
 	if !opts.force {
+
 		fmt.Fprintf(streams.Out(), ansi.Warn("WARNING: This action is irreversible.")+`
-By confirming, you will permanently delete the access token.
-Deleting a token will invalidate your credentials on all Docker clients currently authenticated with this token.
+By confirming, you will permanently revoke and delete the access token.
```
Comment (silvin-lubecki) [inline internal/commands/token/rm.go:72]: About rephrasing the warning message, the original intent was to match Docker Hub UX:
Screenshot 2022-04-13 at 09 55 07

**Review by silvin-lubecki — COMMENTED** [review]
Logic looks good to me, just a small change needed in the warning message 👍 
Thanks for your PR @converge 🙏

**Comment by converge** [comment]
> Logic looks good to me, just a small change needed in the warning message 👍
> Thanks for your PR @converge 🙏

Tks again for the review, these little details make a good difference in the overall user experience.

**Review by silvin-lubecki — APPROVED** [review]
LGTM 🎉
