### PR TITLE
fix the error prints on normal command cancelation

### LINKED ISSUE #54: ^C outputs usage
If you ^C an operation it prints out the usage.

```
hub-tool org ls
^CError: Get "https://hub.docker.com/v2/orgs/docker/groups/automatedreadwrite/members/": context canceled
Usage:
  hub-tool org ls [flags]

Flags:
      --format string   Print values using a custom format ("json")
  -h, --help            help for ls

```

### PR DESCRIPTION
**Pull request by moshebe**
**- What I did**
Fixed the error prints in case of normal cancelation
closes #54 

**- How I did it**
Exported the cancel error and add a check when the cobra command run handler

**- How to verify it**
Run one of the commands e.g. `hub-tool login` and instead of entering Username as expected just press ^C.
No print like those should appear:
`Username: ^CError: canceled`

**- Description for the changelog**

Fix graceful shutdown handling

**- A picture of a cute animal (not mandatory)**

### CODE REVIEW

File: internal/login/login.go [hunk 1]
```diff
@@ -35,6 +35,9 @@ import (
 	"github.com/docker/hub-tool/internal/hub"
 )
 
+// ErrCanceled represents a normally canceled operation
+var ErrCanceled = errors.New("canceled")
```
Comment (rumpl) [inline internal/login/login.go:39]: This error is present 3 times in the change, we could create a package `errdefs` and reuse it?

**Comment by rumpl** [comment]
Looking good, just one small nit

File: internal/login/login.go (hunk 1 above)
Comment (moshebe) [reply internal/login/login.go:39]: I also thought about it. and eventually decided to put it under the command's package because I assume we may want to distinguish between login cancel error and other commands.
IMHO, one package/file that contains is less elegant for this use-case...

However, it's a minor change - let me know what do you prefer and I will set it up

Comment (rumpl) [reply internal/login/login.go:39]: My thinking was: if we have one error for the case when the user cancels the current action then we can [in main.go](https://github.com/docker/hub-tool/blob/main/main.go#L73) handle that error and return the right exit code (130).

Comment (moshebe) [reply internal/login/login.go:39]: I got you, missed the exit code part, in this case your suggestion sounds pretty good 👍 

There is a tricky part here, if we will return an error from the cobra handler the error will be printed (cobra - command.go:941) unless we will turn off the `SilenceErrors` which I don't think it's a good idea because other errors won't be displayed.

Do you have any other idea besides making the changes in the cobra library?

Comment (rumpl) [reply internal/login/login.go:39]: Ah right! The errors, indeed :)

In compose-cli we do [silence the errors](https://github.com/docker/compose-cli/blob/main/cli/main.go#L106) but then we [print them manually](https://github.com/docker/compose-cli/blob/main/cli/main.go#L245).

Comment (moshebe) [reply internal/login/login.go]: Anyway, I made the changes you suggested with the errors declaration.
For the silence-errors stuff, I think it would be better to be discussed in a separate issue considering if the exit-code handling is worth those changes.

Comment (rumpl) [reply internal/login/login.go]: Thanks! @silvin-lubecki will review this tomorrow, and hopefully it will be merged then :)

Thanks!

File: internal/commands/login.go [hunk 2]
```diff
@@ -48,9 +49,14 @@ func newLoginCmd(streams command.Streams, store credentials.Store, hubClient *hu
 			if len(args) > 0 {
 				username = args[0]
 			}
-			if err := login.RunLogin(cmd.Context(), streams, hubClient, store, username); err != nil {
+			err := login.RunLogin(cmd.Context(), streams, hubClient, store, username)
+			if err != nil {
+				if err == errdef.ErrCanceled {
```
Comment (silvin-lubecki) [inline internal/commands/login.go:54]: nit: I guess we should check the error using [errors.Is](https://golang.org/pkg/errors/#Is)

File: internal/commands/repo/rm.go [hunk 3]
```diff
@@ -52,7 +53,11 @@ func newRmCmd(streams command.Streams, hubClient *hub.Client, parent string) *co
 			metrics.Send(parent, rmName)
 		},
 		RunE: func(cmd *cobra.Command, args []string) error {
-			return runRm(cmd.Context(), streams, hubClient, opts, args[0])
+			err := runRm(cmd.Context(), streams, hubClient, opts, args[0])
+			if err == nil || err == errdef.ErrCanceled {
```
Comment (silvin-lubecki) [inline internal/commands/repo/rm.go:57]: nit: Use `errors.Is` here too 😇

File: internal/commands/tag/rm.go [hunk 4]
```diff
@@ -52,7 +52,11 @@ func newRmCmd(streams command.Streams, hubClient *hub.Client, parent string) *co
 			metrics.Send(parent, rmName)
 		},
 		RunE: func(cmd *cobra.Command, args []string) error {
-			return runRm(cmd.Context(), streams, hubClient, opts, args[0])
+			err := runRm(cmd.Context(), streams, hubClient, opts, args[0])
+			if err == nil || err == errdef.ErrCanceled {
```
Comment (silvin-lubecki) [inline internal/commands/tag/rm.go]: image

**Comment by silvin-lubecki** [comment]
@moshebe the linter is complaining
```
Error: internal/commands/repo/rm.go:23: File is not `goimports`-ed (goimports)
	"github.com/pkg/errors"
```

File: internal/commands/tag/rm.go (hunk 4 above)
Comment (moshebe) [reply internal/commands/tag/rm.go]: 😂
Fixed the 3 places where the `errors.Is` was missing. 
Thanks @silvin-lubecki

**Review by silvin-lubecki — APPROVED** [review]
LGTM, thanks a lot @moshebe 🙏
