### PR TITLE
Fixes #178

### LINKED ISSUE #178: repo rm command not working
**Description**

The `hub-tool repo rm my-username/my-repo` command is giving me `Error: Delete "https://hub.docker.com/v2/repositories/my-username/my-repo/": EOF` error.

When I tried with `hub-tool repo rm my-repo` (without my-username), I got `Error: operation not permitted` error.

**Steps to reproduce the issue:**
1. Run `hub-tool login`
2. Run `hub-tool repo rm USER/REPO`
3. Or run `hub-tool repo rm REPO`

**Describe the results you received:**

See above

**Describe the results you expected:**

The repo get deleted successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Always happen

**Output of `hub-tool --version`:**

```
Docker Hub Tool v0.4.1, build 5051946
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 75
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: G4YM:Y5PD:7E3Z:PJZS:URBX:MOMC:I7NO:5UUV:DLRK:7VKF:GQ7W:GHRL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Username: zulhfreelancer
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* OS: Mac OS 10.15.7
* Install method: direct download from [release page](https://github.com/docker/hub-tool/releases/tag/v0.4.1) and moved the binary to `/usr/local/bin`

### PR DESCRIPTION
**Pull request by converge**
**- What I did**

Fix one of the bugs reported by https://github.com/docker/hub-tool/issues/178 and improve error handling for the repository deletion. The repository cannot be deleted if Docker Hub username is not provided.

how to reproduce the issue:
```
# 1
hub-tool repo rm test
# 2
the output is a successful message because the HTTP response is not validated.
```

**- How I did it**

1. The fix includes the username to the repository deletion endpoint
2. Adds new error handler for HTTP Not Found
3. In case the repository doesn't exist, there is a proper error response: `Error: resource not found`
4. Improves the error message, making it clear which repository was deleted
5. Improve how URL is built before requesting the API

**- How to verify it**

The impacted changes can be tested via:

`./hub-tool repo rm repository-name`

**- Description for the changelog**

Allow repository deletion by using repository name only (without username) and add error handler for resource/repository not found.

p.s: this PR doesn't fix one of the reported errors:

`Error: operation not permitted error`

Since this is an ongoing discussion: https://github.com/docker/hub-tool/issues/172

**- A picture of a cute animal (not mandatory)**

### CODE REVIEW

File: pkg/hub/repositories.go [hunk 1]
```diff
@@ -77,12 +76,17 @@ func (c *Client) GetRepositories(account string) ([]Repository, int, error) {
 
 //RemoveRepository removes a repository on Hub
 func (c *Client) RemoveRepository(repository string) error {
-	req, err := http.NewRequest("DELETE", c.domain+fmt.Sprintf(DeleteRepositoryURL, repository), nil)
+	repositoryUrl := fmt.Sprintf("%s%s%s/%s/", c.domain, RepositoriesURL, c.account, repository)
```
Comment (silvin-lubecki) [inline pkg/hub/repositories.go:79]: I'd like to point out that prefixing the user account to the repository name by default won't work. You can be part of many organizations, and so you may need to specify the full repository name `<org>/<repo>`.
With this code it will result with `<user>/<org>/<repo>`.
Maybe we should parse the `repository` argument, check if an org (or user) is already specified, and if not prefix with user account ? WDYT ?

**Review by silvin-lubecki — CHANGES_REQUESTED** [review]
Hello @converge, thank you for your PR 🙏 
The new error handling is good to me, but not the account info part (see my other comment) 👍

File: pkg/hub/repositories.go (hunk 1 above)
Comment (converge) [reply pkg/hub/repositories.go:79]: @silvin-lubecki tks for the review. That's true, I don't have access to a <org>/paid account, and I couldn't test this use-case. I'll look for a paid account, and follow up with your comments.

**Comment by silvin-lubecki** [comment]
By the way @converge the linter is complaining 🦁 
https://github.com/docker/hub-tool/runs/5968337414?check_suite_focus=true#step:5:11

File: pkg/hub/repositories.go (hunk 1 above)
Comment (converge) [reply pkg/hub/repositories.go]: @silvin-lubecki I slept on that, and I believe the cleanest way to solve is to follow a pattern for the deletion. Allowing the user to not provide a prefix(username), and request the user to provide the organization name could be confusing.

My last commit makes it clear the user needs to always provide a prefix (username or organization name) together with the repository name. WDYT?

p.s: it was tested with user repo. and organization repo. Lint issue was also fixed, I wasn't aware of the linting 🙈

File: internal/commands/repo/rm.go [hunk 2]
```diff
@@ -47,7 +47,7 @@ type rmOptions struct {
 func newRmCmd(streams command.Streams, hubClient *hub.Client, parent string) *cobra.Command {
 	var opts rmOptions
 	cmd := &cobra.Command{
-		Use:                   rmName + " [OPTIONS] REPOSITORY",
+		Use:                   rmName + " [OPTIONS] USERNAME(OR)ORGANIZATION NAME/REPOSITORY",
```
Comment (silvin-lubecki) [inline internal/commands/repo/rm.go:50]: question: I wonder 🤔 if we should just rephrase to:
```
NAMESPACE/REPOSITORY
```
WDYT ?

Comment (converge) [reply internal/commands/repo/rm.go]: tks again for the guidance, it's great to have your support!

**Review by silvin-lubecki — APPROVED** [review]
LGTM
